[parity]
mode = "active"
mode_timeout = 300
mode_alarm = 3600
no_persistent_txqueue = true
chain = "dev"
base_path = "/parity/.local/share/io.parity.ethereum"
db_path = "/parity/.local/share/io.parity.ethereum/chains"
keys_path = "/parity/.local/share/io.parity.ethereum/keys"

[network]
port = 30303
allow_ips = "all"
max_pending_peers = 512

[rpc]
disable = false
port = 8545
interface = "0.0.0.0"
hosts = ["*"]
apis = ["web3", "eth", "net","parity","parity_accounts","personal", "traces", "secretstore", "parity_pubsub"]

